# Generated by Django 4.2.13 on 2024-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('course', models.CharField(choices=[('BS-CS', 'BS in Computer Science'), ('BS-DS', 'BS in Data Science'), ('BS-IT', 'BS in Information Technology'), ('BS-IS', 'BS in Information Systems')], max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
